#define C_WINDOW_TITLE "Transcoder Audio Edition"

#define C_WINDOW_WIDTH 730
#define C_WINDOW_HEIGHT 600

#define C_LABLE_WIDTH 100
#define C_LABLE_HEIGHT 25

#define C_ENTRY_WIDTH 60
#define C_ENTRY_HEIGHT 25

#define C_MIN_AUDIO_BITRATE 16
#define C_MAX_AUDIO_BITRATE 1440

#define C_MIN_AUDIO_VOLUME 0
#define C_MAX_AUDIO_VOLUME 2048
#define C_DEFAULT_AUDIO_VOLUME 256

#define C_DEFAULT_AUDIO_BITRATE 128
#define C_DEFAULT_AUDIO_BITRATE_STR "128000"

#define C_VERSION "0.0.6"

#define C_NUM_A_CODECS 7
